import './global.scss';
import Script from 'next/script';
import { Providers } from '../components/Providers';

export const metadata = {
  title: 'Welcome to furry-family-fe',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <Script src="https://www.googletagmanager.com/gtag/js?id=G-X6RSMR3XJX" />
      <Script id="google-analytics">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-X6RSMR3XJX');
        `}
      </Script>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
